### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Pheotis** [PhantomMC/PhantomServer#1]
### Core-Features
- [x] Async Processing
- [ ] Sender for [Bstats Data](https://github.com/the-lockedcraft-legacy-organization/PhantomServer/blob/main/pha_bstats.py).
- [x] Improved UI
- [ ] Improved Documentation

### Possible Additional Features
- [ ] Support for [very old versions](https://wiki.vg/Server_List_Ping#1.6)
- [ ] Support for [local area network broadcasting](https://wiki.vg/Server_List_Ping#Ping_via_LAN_.28Open_to_LAN_in_Singleplayer.29)
- [ ] Support for [bedrock server protocol](https://wiki.vg/Pocket_Edition_Protocol_Documentation)
- [ ] Port for C and/or Shell?
