### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Thorinwasher** [PhantomMC/PhantomServer#3]
## Tasks and the order they should be finished
- [x] Works for localhost connection
- [x] Show all possible server messages
- [x] Show logo
- [x] Have a config
- [x] Store all logs
- [x] Async Processing
- [x] Improved UI
- [ ] Store unique users
- [ ] Sender for [Bstats Data](https://github.com/the-lockedcraft-legacy-organization/PhantomServer/blob/main/pha_bstats.py).
- [ ] Works for non localhost connections (haven't tried yet)
- [ ] Search and find no issues
- [ ] Improved Documentation
